version: '3.8'
services:
  frontend:
    build:
      context: ../frontend-For-Survey
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ../frontend-For-Survey:/app
  nestjs_api:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - .:/app
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT} 
    environment:
      - POSTGRES_ROOT_PASSWORD=root_password_123
      - POSTGRES_DB=${DATABASE_NAME} 
      - POSTGRES_USER=${DATABASE_USERNAME} 
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD} 
      - POSTGRES_TCP_PORT=${DATABASE_PORT} 